class VmContext:
    def __init__(self):
        pass

    VLAN_MAPPING = 'VLAN_MAPPING'
    VM_UUID = 'VM_UUID'
    VCENTER_NAME='VCENTER_NAME'
    NETWORK_NAME = 'NETWORK_NAME'
    VLAN_ID = 'VLAN_ID'
    VLAN_SPEC_TYPE = 'VLAN_SPEC_TYPE'
    VNIC_NAME = 'VNIC_NAME'
    NETWORKS = 'NETWORKS'
